### ISSUE TITLE
麻烦问下，返回的结果和实际不同？

### ISSUE THREAD

**Issue by Coding-01** [iceyhexman/onlinetools#13]
![1111](https://user-images.githubusercontent.com/42321502/61208487-5a3c5580-a6ac-11e9-9edb-9d2e8a613786.png)
这个显示结果前面说”未发现异常“，后面又说的弱口令漏洞和未授权漏洞，这是说的有漏洞还是没漏洞？

**Comment by hansion731** [comment]
没漏洞  有漏洞会提示发现异常

**Comment by Coding-01** [comment]
好的    明白    感谢
